add content index.html
milodevhh/personal-website pull request #1
Opened 2023-06-22 05:32 UTC by milodevhh

Hey folks please check my first pull request for "personal-website". Thank you ;) & Cheers

2023-06-22 06:49 UTC, ninaassmann requested changes
some tips, but looks good for me

2023-06-22 06:49 UTC, ninaassmann commented on index.html
> +        <!--When clicking on these element, nothing happens! But I want to be redirected to the other websites. Why is it not working?-->
wahrscheinlich hast du versucht, den Link aus der VS Code Preview zu öffnen, dann öffnet sich allerdings erstmal nur dein Browser mit der selben Seite. Hier funktionieren dann aber die Links. Ich glaub, das hängt mit der Vorschau in VS Code zusammen

2023-06-22 06:49 UTC, ninaassmann commented on index.html
> +        >
hast du die extension prettier an? hier ist der closing > vom </a> in die nächste Zeile gerückt. Kein tatsächliches Problem, aber wegen der Übersicht, würde ich es direkt hinter das a verschieben =>
</a> statt
</a
>

2023-06-22 06:49 UTC, ninaassmann commented on index.html
> +            >calendly</a
das gleiche wie oben

2023-06-22 06:49 UTC, ninaassmann commented on index.html
> +          <a href="https://github.com/neuefische" target="_blank">neuefische</a
gleiche wie unten => </a>

2023-06-22 15:38 UTC, milodevhh commented
Hi @ninaassmann if you like please have a lock. Than I will merge and close the branch ... I will can start with a new branch for styles ;) Thanks a lot for your help! Cheers Milo

2023-06-22 16:05 UTC, Faibs7 commented
Looks Great, LGTM
Some Idea :
-You can add some images for the platforms Github and Linkedin in the imprint and hide the link to the respective page behind it?

2023-06-23 05:33 UTC, milodevhh commented
looks good ...

2023-06-23 05:33 UTC, merged